Main functional
Ben1t0/java-explore-with-me pull request #1
Opened 2022-09-09 23:32 UTC by Ben1t0

2022-09-16 06:16 UTC, sergeymamonov requested changes
Посмотрите, сейчас сборка красная, лучше добиться зеленой сборки. Возможно, нужно удалить модификатор static у поля.
По архитектуре, сейчас есть какая-то сущность, и в пакете для нее лежит все, контроллер, dto и так далее. Не очень удобная модель. Чаще делают слоями, то есть делают пакет контроллеров, пакет dto. В крупных проектах это уже не пакеты, а модули.  И ими проще управлять и проще добавлять зависимости и так далее. Поэтому предложил бы рассмотреть перемещение контроллеров в отдельный пакет, классов сервисов в свой пакет и так далее. Но не настаиваю на изменении, это как вариант для улучшения проекта.
Пакет explorewithme я бы написал через нижние подчеркивания explore_with_me, ведь в других местах написание не слитно, поэтому здесь бы не делал слитного написания.
Местами в названиях методов встречается OrThrow, я бы предложил убрать. Можно сделать валидацию, и результат, который приходит от другого метода проверять в валидаторе. И уже в валидаторе кидать исключение.
Некоторые методы возвращают Collection. Если в таком интерфейсе необходимости нет, то предложил бы заменить на List.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/dto/EventMapper.java
> +    private static StatisticService statisticService;
Посмотрите это поле, возможно его можно сделать не статичным, чтобы проходил конвейер CI

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/controller/AdminController.java
> +    //region /Admin/Users Handlers
По поводу таких комментариев, на мой взгляд, они излишни, так как в следущей строке в аннотации видно, что за эндпоинт. Во-вторых комментарии нужно поддерживать в актуальном состоянии, то есть изменился эндпоинт, нужно изменить комментарий. А очень легко забыть изменить комментарий. И вот уже ситуация, когда комментарий будет не соответствовать действительности. Поэтому смотрите сами, хотите оставляйте, но на мой взгляд они избыточны.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/controller/AdminController.java
> +                                                  @RequestParam(value = "from", defaultValue = "0") Integer from,
Насколько я понимаю, то это два параметра для пагинации. Будет проще понимать, если параметр будет называться не from, а page. Но это если я правильно понял замысел.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/controller/AdminController.java
> +    public void deleteCategory(@PathVariable Long catId) {
Лучше сделать более информативное название переменной (написать полностью слово, без сокращения). Посмотрите по коду, встречаются и в других местах переменные с аналогичными названиями.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/category/service/CategoryService.java
> +    Collection<CategoryDto> getAll(Integer from, Integer size);
Здесь действительно нужно возвращать коллекцию? Может имеет смысл сократить до List?

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/service/EventService.java
> +    Collection<ShortEventDto> findPublicEvent(String text, Collection<Long> catIds, boolean paid,
Когда получается, что в метод нужно передать много параметров, то эти параметры собирают в один объект и тогда в метод передают этот один объект. И получается, что метод уже принимает не 9 параметров, а один. Плюс если потребуется передать десятый параметр в метод, его сигнатура не ломается, а добавляется десятое поле в созданный класс. Но это по желанию, не настаиваю на этом изменении. Из серии было бы лучше.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/service/EventServiceImpl.java
> +    public Collection<ShortEventDto> findPublicEvent(String text, Collection<Long> catIds, boolean paid,
В классе много разных проверок, предложил бы выделить всю валидацию отдельно в класс  валидатора. И в нем уже отдельный методы проверки одного, второго и так далее.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/partisipationrequest/dto/RequestMapper.java
> +        return ParticipationRequestDto.builder()
На всякий случай предложил бы добавить проверку, что приходящий request не null, так как если придет null, то ниже будет NPE.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/statistic/dto/HitDto.java
> +public class HitDto {
Не очень понял это сокращение или слово хит? Да и для следующего класса тоже предложил бы написать полностью.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +//TODO: check functions
Не нужно оставлять тудушек в дипломном проекте.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explorewithme/utils/ErrorStatus.java
> +public enum ErrorStatus {
Статусы есть в разных библиотеках, самому делать это не самая лучшая практика. Лучше взять из библиотеки.

2022-09-16 06:16 UTC, sergeymamonov commented on ewm-service/src/test/java/ru/practicum/explorewithme/event/dto/DtoJsonTest.java
> +    public void testDeserializeDto() {
Предложил бы добавить в тест проверку (assert...)

2022-09-16 06:16 UTC, sergeymamonov commented on statistic-service/src/main/java/ru/practicum/statistic/service/StatServiceImpl.java
> +        //Map<String, List<EndpointHit>> hits = repository.findAllByUriInAndTimestampBetween(uris, start, end).stream()
Закомментированного кода не должно быть в проекте.

2022-09-16 08:04 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/controller/AdminController.java
> +    //region /Admin/Users Handlers
Эти метки позволяют в Intellij IDEA свернуть блок кода между region и endregion

2022-09-16 08:05 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/controller/AdminController.java
> +                                                  @RequestParam(value = "from", defaultValue = "0") Integer from,
Это из спецификации, from это офсет по количеству элементов от 0.

2022-09-16 10:11 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/dto/EventMapper.java
> +    private static StatisticService statisticService;
1) По поводу explore_with_me я думал что нельзя использовать в названии пакетов нижний прочерк по принятым правилам, но поменяю.
2) Там не совсем валидация, там основная идея функции взять из репозитория объект и если его там нет кинуть мое собственное исключение. Если делать валидацию то придется 2 раза в базу ходить при каждом запросе.

2022-09-16 11:06 UTC, Ben1t0 commented
1. По поводу explore_with_me я думал что нельзя использовать в названии пакетов нижний прочерк по принятым правилам, но поменяю.
2. Там не совсем валидация, там основная идея функции взять из репозитория объект и если его там нет кинуть мое собственное исключение. Если делать валидацию то придется 2 раза в базу ходить при каждом запросе.

2022-09-16 11:49 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/dto/EventMapper.java
> +    private static StatisticService statisticService;
готово

2022-09-16 11:49 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/admin/controller/AdminController.java
> +    public void deleteCategory(@PathVariable Long catId) {
готово

2022-09-16 11:49 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/category/service/CategoryService.java
> +    Collection<CategoryDto> getAll(Integer from, Integer size);
готово

2022-09-16 11:50 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/service/EventService.java
> +    Collection<ShortEventDto> findPublicEvent(String text, Collection<Long> catIds, boolean paid,
готово

2022-09-16 12:25 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/event/service/EventServiceImpl.java
> +    public Collection<ShortEventDto> findPublicEvent(String text, Collection<Long> catIds, boolean paid,
Готово

2022-09-16 12:25 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/partisipationrequest/dto/RequestMapper.java
> +        return ParticipationRequestDto.builder()
готово

2022-09-16 12:25 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/statistic/dto/HitDto.java
> +public class HitDto {
готово

2022-09-16 12:26 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/user/service/UserServiceImpl.java
> +//TODO: check functions
забыл проверить, убрал

2022-09-16 12:26 UTC, Ben1t0 commented on ewm-service/src/main/java/ru/practicum/explorewithme/utils/ErrorStatus.java
> +public enum ErrorStatus {
в первой ревизии ТЗ нужно было свой написать. Убрал.

2022-09-16 12:26 UTC, Ben1t0 commented on ewm-service/src/test/java/ru/practicum/explorewithme/event/dto/DtoJsonTest.java
> +    public void testDeserializeDto() {
сделал

2022-09-16 12:27 UTC, Ben1t0 commented on statistic-service/src/main/java/ru/practicum/statistic/service/StatServiceImpl.java
> +        //Map<String, List<EndpointHit>> hits = repository.findAllByUriInAndTimestampBetween(uris, start, end).stream()
Забыл убрать. Готово.

2022-09-16 12:39 UTC, Ben1t0 commented
Я исправил все замечания (вроде). Старую ошибку убрал но все равно CI не проходят, приложение стартует нормально но там какой то косяк в скрипте. Такая ошибка не у меня одного.

2022-09-16 12:55 UTC, Ben1t0 commented
Ошибки исправил. Автотесты в процессе исправления поэтому плашка красная.

2022-09-20 11:12 UTC, sergeymamonov approved these changes

2022-09-20 11:12 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/model/request/RequestMapper.java
> +        if (request != null) {
Проще делать 
if (request != null) {
   return null;
}

Во-первых, так код метода получается не сдвинутым на отступ, во-вторых сразу видна проверка и не нужен блок else.

2022-09-20 11:12 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/service/event/EventServiceImpl.java
> +            if (event.getParticipantLimit() > 0) {
Можно объединить if. Они идут последовательно и блоки else у них одинаковые.

2022-09-20 11:12 UTC, sergeymamonov commented on ewm-service/src/main/java/ru/practicum/explore_with_me/service/event/EventServiceImpl.java
> +    public List<FullEventDto> findEvents(Collection<Long> userIds, Collection<EventState> states,
В метод передается много аргументов. Лучше сделать отдельный класс, в котором поля будут передаваемые в метод объекты. И тогда метод будет принимать только один объект.

2022-09-21 09:57 UTC, merged